services:
  # conteneur recepteur
  api-recepteur:
    container_name: apirecepteur
    build: .
    env_file: .env
    networks:
      - pynet
    volumes:
      - ./src:/app/src
    depends_on:
      - redis  # on évite que l'API plante si le conteneur redis n'est pas encore prêt
    command: ["uv" ,"run", "uvicorn" ,"src.API.streamrecepteur:app", "--host", "0.0.0.0" , "--port", "8000"]
    ports:
      - "${API_PORT}:${API_PORT}"

  # conteneur envoi
  stream-envoi:
    container_name: streamenvoi
    build: .
    environment:
      - API_URL=http://api-recepteur:8000
    env_file: .env
    depends_on:
      - api-recepteur
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    command: ["uv", "run", "python", "src/API/streamenvoi.py"]
    networks:
        - pynet


  # streamlit
  dashboard:
    container_name: dashboard
    build: .
    env_file: .env
    depends_on:
      - api-recepteur
    networks:
      - pynet
    environment:
      - API_URL=http://api-recepteur:8000
    command: ["uv" ,"run","streamlit", "run", "src/dashboard/dashboard.py", "--server.address", "0.0.0.0"]
    volumes:
      - ./src:/app/src
    ports:
      - "${DASHBOARD_PORT}:${DASHBOARD_PORT}"

  # promotheus, grafana et cadvisor pour le monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped #prometheus restarts automatically if it crashes or the system reboots
    env_file: .env
    networks:
      - pynet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - pynet

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    networks:
      - pynet


  # conteneur redis
  redis:
    image: redis:latest             # téléchargement de l'image officielle 
    container_name: redis-service
    networks:
      - pynet
    env_file: .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:        
      - redis_data:/data        


  # conteneur worker BigQuery
  worker-bigquery:
      build: . #/api-recepteur
      container_name: worker-bigquery
      command: python src/API/worker_bq.py
      depends_on:
        - redis
      networks:
        - pynet
      environment:
        - REDIS_HOST=redis


volumes:
  redis_data:
  grafana-storage:
  
 
networks:
  pynet:
    driver: bridge
